### ISSUE TITLE
 incorrect description

### ISSUE THREAD

**Issue by forostm** [KaOS-Community-Packages/mediathek#2]
incorrect description

**Comment by ShalokShalom** [comment]
and what exactly, please?

**Comment by forostm** [comment]
Now, the description of the repo are install  instructions. It is not a real description of package.

**Comment by ShalokShalom** [comment]
its both: java-based downloader for several german broadcasting media centers (mediatheken), including ARD, ZDF, Arte, 3Sat, SWR, BR, MDR, NDR, WDR, HR, RBB, ORF, SF

**Comment by raul338** [comment]
Done
